TR001 error handing and axios completed
techameed/reactthervu pull request #5
Opened 2020-04-20 07:51 UTC by DakshinaJB

app.axios.js - i have created a wrapper for axios.
error.boundary.js- created a wrapper for error.
dialog.box.js - dispalying error in a dialog box
dialog.box.css- style for dialog box.

2020-04-20 09:58 UTC, sairamyakannan commented on src/axiosAndErrorhandling/error.boundary.js
> +            axios.interceptors.request.use(req => {
req to request

2020-04-20 09:59 UTC, sairamyakannan commented on src/axiosAndErrorhandling/error.boundary.js
> +                   // {this.state.error.message}
why commented line ?

2020-04-20 10:01 UTC, sairamyakannan commented on src/axiosAndErrorhandling/error.boundary.js
> +         openModal() {
Gave extra space in line number 13

2020-04-20 10:03 UTC, sairamyakannan commented on src/axiosAndErrorhandling/dialog.box.js
> +    handleOpenModal () {
Should not use handle

2020-04-20 10:04 UTC, sairamyakannan commented on src/axiosAndErrorhandling/dialog.box.js
> +    handleCloseModal () {
Should not use handle

2020-04-20 10:05 UTC, sairamyakannan commented on src/axiosAndErrorhandling/dialog.box.js
> +    render () {
Make sure your Indentations right

2020-04-20 10:11 UTC, sairamyakannan commented on src/axiosAndErrorhandling/dialog.box.js
> +    handleOpenModal () {
No space between methods handleOpenModel()

2020-04-20 10:12 UTC, sairamyakannan commented on src/axiosAndErrorhandling/dialog.box.js
> +    render () {
Space between render () ?

2020-04-20 10:13 UTC, sairamyakannan commented on src/axiosAndErrorhandling/error.boundary.js
> +                <>
<> ?

2020-04-20 11:26 UTC, karthick1696 commented on src/axiosAndErrorhandling/dialog.box.js
> +    handleOpenModal () {
please don't start method name with "handle", prefer "on".
combine open and close methods of modal into one, since it has same functional behaviour

2020-04-20 11:26 UTC, karthick1696 commented on src/axiosAndErrorhandling/dialog.box.js
> +             className="classes.Modal"
classes.Modal won't work when we wrapped with quotes, wrap it with curly braces

2020-04-20 11:26 UTC, karthick1696 commented on src/axiosAndErrorhandling/dialog.box.js
> +            <div><p>{this.props.error}</p></div>
since p itself a block level element, don't wrap it in div

2020-04-20 11:26 UTC, karthick1696 commented on src/axiosAndErrorhandling/dialog.box.js
> +import React ,{Component} from 'react';
Follow some standards, 
1. don't leave space before comma
2. leave space before and after the curly braces in named imports

2020-04-20 11:26 UTC, karthick1696 commented on src/axiosAndErrorhandling/dialog.box.js
> +export default modal;
always leave a new line at EOF

2020-04-20 11:26 UTC, karthick1696 commented on src/axiosAndErrorhandling/error.boundary.js
> +         openModal() {
what is the use of this function?

2020-04-20 11:29 UTC, DakshinaJB commented on src/axiosAndErrorhandling/error.boundary.js
> +         openModal() {
i have changed it. It wont come there

2020-04-21 10:16 UTC, muruganvenkatesan requested changes

2020-04-21 10:16 UTC, muruganvenkatesan commented on src/axiosAndErrorhandling/dialog.box.js
>  import classes from './dialog.box.css';
File name is not separated by .(dot)
Js file name suffix with container

2020-04-21 10:23 UTC, closed without merging